#ifndef SARW_CONFIG_H
#define SARW_CONFIG_H

//Configuration definitions processed by Cmake
//	Do not edit config.h, it is generated by Cmake
//	Edit config.in.h instead

#include <core/Util.h>

#define PACKAGE_NAME "${CPACK_PACKAGE_NAME}"
#define VERSION_STRING "${VERSION_STRING}"
#define GIT_HASH "${GIT_HASH}"

#endif // SARW_CONFIG_H
